/**
 * AutoHub - Mock Data Source
 */

const VEHICLES = [
    {
        id: 'v1',
        name: 'Tata Ace Gold',
        brand: 'Tata',
        model: 'Ace',
        price: 480000,
        type: 'Commercial Vehicle',
        bodyType: 'Pick Up',
        year: 2023,
        km: 5000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Pune',
        exteriorColor: 'White',
        interiorColor: 'Grey',
        listingAgeDays: 2,
        condition: 'New',
        distance: 15,
        sellerName: 'Deshpande Commercials, Pune',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&q=80&w=600',
        description: 'Reliable and durable mini truck for all your business needs.',
        variant: 'Diesel CX',
        rto: 'MH-12',
        emi: '9,500',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Business Ready',
        specs: { engine: '2-Cylinder 700cc', power: '20 hp', payload: '710 kg' }
    },
    {
        id: 'v2',
        name: 'Eicher Pro 2049',
        brand: 'Eicher',
        model: 'Pro 2049',
        price: 1350000,
        type: 'Heavy Vehicle',
        bodyType: 'Van',
        year: 2021,
        km: 45000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Mumbai',
        exteriorColor: 'White',
        interiorColor: 'Black',
        listingAgeDays: 10,
        condition: 'Used',
        distance: 45,
        sellerName: 'Global Heavy Equipments, Mumbai',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&q=80&w=600',
        description: 'Robust truck with premium load capacity.',
        variant: 'Pro 2049 2775/FSD',
        rto: 'MH-04',
        emi: '25,855',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Assurred',
        isAuction: true,
        specs: { engine: '2.0L Diesel', power: '100 bhp', payload: '2.5 Ton' }
    },
    {
        id: 'v3',
        name: 'Toyota Innova Crysta',
        brand: 'Toyota',
        model: 'Innova',
        price: 2950000,
        type: 'Passenger Vehicle',
        bodyType: 'MUV',
        year: 2020,
        km: 65000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: 'Second Owner',
        location: 'Bangalore',
        exteriorColor: 'Silver',
        interiorColor: 'Beige',
        listingAgeDays: 20,
        condition: 'Used',
        distance: 120,
        sellerName: 'Capital Motors, Bangalore',
        dealerTrustStatus: 'Non-Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=600',
        description: 'Comfortable fleet passenger vehicle.',
        variant: '2.4 G 7 STR',
        rto: 'KA-03',
        emi: '56,311',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Fleet Ready',
        specs: { engine: '2.4L Diesel', power: '148 bhp', mileage: '12 kmpl' }
    },
    {
        id: 'v4',
        name: 'Ashok Leyland Dost+',
        brand: 'Ashok Leyland',
        model: 'Dost',
        price: 750000,
        type: 'Commercial Vehicle',
        bodyType: 'Pick Up',
        year: 2022,
        km: 15000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Delhi',
        exteriorColor: 'White',
        interiorColor: 'Grey',
        listingAgeDays: 5,
        condition: 'Used',
        distance: 80,
        sellerName: 'Northwest Commercials, Delhi',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&q=80&w=600',
        description: 'Premium light commercial vehicle.',
        variant: 'LS',
        rto: 'DL-01',
        emi: '13,861',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Low kms driven',
        isAuction: true,
        specs: { engine: '1.5L Diesel', power: '80 bhp', payload: '1500 kg' }
    },
    {
        id: 'v5',
        name: 'Honda Activa 6G',
        brand: 'Honda',
        model: 'Activa',
        price: 65000,
        type: 'Two-Wheeler',
        bodyType: 'Scooter',
        year: 2022,
        km: 15000,
        fuel: 'Petrol',
        transmission: 'Automatic',
        owner: 'First Owner',
        location: 'Pune',
        exteriorColor: 'Blue',
        interiorColor: 'Black',
        listingAgeDays: 35,
        condition: 'Used',
        distance: 10,
        sellerName: 'Deshpande Commercials, Pune',
        dealerTrustStatus: 'Trusted Dealer',
        // Example of a fallback image handling trigger (leaving empty to test fallback CSS)
        image: '',
        description: 'Ideal two-wheeler for delivery fleets.',
        variant: 'Standard',
        rto: 'MH-14',
        emi: '1,542',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Bulk Available',
        specs: { engine: '109.51cc', power: '7.68 bhp', mileage: '50 kmpl' }
    },
    {
        id: 'v7',
        name: 'Hyundai Creta',
        brand: 'Hyundai',
        model: 'Creta',
        price: 1450000,
        type: 'Passenger Vehicle',
        bodyType: 'SUV',
        year: 2023,
        km: 12000,
        fuel: 'Diesel',
        transmission: 'Automatic',
        owner: 'First Owner',
        location: 'Delhi',
        exteriorColor: 'Black',
        interiorColor: 'Black',
        listingAgeDays: 1,
        condition: 'Used',
        distance: 25,
        sellerName: 'Elite Motors, Delhi',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=600',
        description: 'Top-selling premium SUV with panoramic sunroof.',
        variant: 'SX (O) AT',
        rto: 'DL-08',
        emi: '28,500',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Mint Condition',
        specs: { engine: '1.5L CRDi', power: '113 bhp', mileage: '18 kmpl' }
    },
    {
        id: 'v8',
        name: 'Maruti Suzuki Dzire',
        brand: 'Maruti Suzuki',
        model: 'Dzire',
        price: 820000,
        type: 'Passenger Vehicle',
        bodyType: 'Sedan',
        year: 2022,
        km: 25000,
        fuel: 'Petrol + CNG',
        transmission: 'Manual',
        owner: 'First Owner',
        location: 'Ahmedabad',
        exteriorColor: 'Grey',
        interiorColor: 'Beige',
        listingAgeDays: 12,
        condition: 'Used',
        distance: 60,
        sellerName: 'Sahyog Motors, Ahmedabad',
        dealerTrustStatus: 'Trusted Dealer',
        // Example for testing broken image loading fallback
        image: 'broken-link.jpg',
        description: 'Perfect family sedan with high fuel efficiency.',
        variant: 'ZXI CNG',
        rto: 'GJ-01',
        emi: '15,200',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'High Fuel Efficient',
        specs: { engine: '1.2L K12', power: '76 bhp', mileage: '31 km/kg' }
    },
    {
        id: 'v9',
        name: 'Mahindra Thar',
        brand: 'Mahindra',
        model: 'Thar',
        price: 1650000,
        type: 'Passenger Vehicle',
        bodyType: 'SUV',
        year: 2023,
        km: 8000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Pune',
        exteriorColor: 'Red',
        interiorColor: 'Black',
        listingAgeDays: 4,
        condition: 'Used',
        distance: 5,
        sellerName: 'Deshpande Commercials, Pune',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=600',
        description: 'Iconic 4x4 SUV for adventure and business.',
        variant: 'LX 4-Str Hard Top',
        rto: 'MH-12',
        emi: '32,450',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Off-Road Ready',
        specs: { engine: '2.2L mHawk', power: '130 bhp', torque: '300 Nm' }
    },
    {
        id: 'v10',
        name: 'Tata Prima 5530.S',
        brand: 'Tata',
        model: 'Prima',
        price: 4200000,
        type: 'Heavy Vehicle',
        bodyType: 'Trailer',
        year: 2022,
        km: 85000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Hyderabad',
        exteriorColor: 'Yellow',
        interiorColor: 'Grey',
        listingAgeDays: 15,
        condition: 'Used',
        distance: 200,
        sellerName: 'Deccan Logistics, Hyderabad',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1586191552066-d52dd1e3af86?auto=format&fit=crop&q=80&w=600',
        description: 'High performance trailer for long-haul transportation.',
        variant: 'Prima 5530.S 6x4',
        rto: 'TS-09',
        emi: '85,000',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Heavy Hauler',
        specs: { engine: '6.7L Cummins', power: '300 hp', payload: '55 Ton' }
    },
    {
        id: 'v11',
        name: 'Royal Enfield Classic 350',
        brand: 'Royal Enfield',
        model: 'Classic',
        price: 195000,
        type: 'Two-Wheeler',
        bodyType: 'Cruiser',
        year: 2021,
        km: 12000,
        fuel: 'Petrol',
        transmission: 'Manual',
        owner: 'Second Owner',
        location: 'Bangalore',
        exteriorColor: 'Black',
        interiorColor: 'Tan',
        listingAgeDays: 8,
        condition: 'Used',
        distance: 50,
        sellerName: 'South Bikes, Bangalore',
        dealerTrustStatus: 'Non-Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=600',
        description: 'Timeless cruiser for local business coordination.',
        variant: 'Chrome Black',
        rto: 'KA-05',
        emi: '4,500',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Vintage Vibe',
        specs: { engine: '349cc', power: '20.2 bhp', mileage: '35 kmpl' }
    },
    {
        id: 'v12',
        name: 'Maruti Suzuki Wagon R',
        brand: 'Maruti Suzuki',
        model: 'Wagon R',
        price: 550000,
        type: 'Passenger Vehicle',
        bodyType: 'Hatchback',
        year: 2023,
        km: 3000,
        fuel: 'CNG',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Mumbai',
        exteriorColor: 'White',
        interiorColor: 'Grey',
        listingAgeDays: 2,
        condition: 'Used',
        distance: 12,
        sellerName: 'Metro Maruti, Mumbai',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
        description: 'Compact hatchback with exceptional fuel economy.',
        variant: 'LXI CNG',
        rto: 'MH-01',
        emi: '10,500',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Urban Specialist',
        specs: { engine: '1.0L K10C', power: '56 bhp', mileage: '34 km/kg' }
    }
];
