/**
 * AutoHub - Mock Data Source
 */

const VEHICLES = [
    {
        id: 'v1',
        name: 'Tata Ace Gold',
        brand: 'Tata',
        price: 480000,
        type: 'Commercial Vehicle',
        year: 2023,
        km: 5000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Pune',
        sellerName: 'Deshpande Commercials, Pune',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1594042878693-514add1d4411?auto=format&fit=crop&q=80&w=400',
        description: 'Reliable and durable mini truck for all your business needs.',
        variant: 'Diesel CX',
        rto: 'MH-12',
        emi: '9,500',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Business Ready',
        specs: {
            engine: '2-Cylinder 700cc',
            power: '20 hp',
            torque: '45 Nm',
            payload: '710 kg'
        }
    },
    {
        id: 'v2',
        name: 'Eicher Pro 2049',
        brand: 'Eicher',
        price: 1350000,
        type: 'Heavy Vehicle',
        year: 2021,
        km: 45000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Mumbai',
        sellerName: 'Global Heavy Equipments, Mumbai',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1626668893632-6f3c4466d22f?auto=format&fit=crop&q=80&w=400',
        description: 'Robust truck with premium load capacity and powerful performance.',
        variant: 'Pro 2049 2775/FSD',
        rto: 'MH-04',
        emi: '25,855',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Assurred',
        specs: {
            engine: '2.0L Diesel',
            power: '100 bhp',
            torque: '285 Nm',
            payload: '2.5 Ton'
        },
        isAuction: true
    },
    {
        id: 'v3',
        name: 'Toyota Innova Crysta (Fleet)',
        brand: 'Toyota',
        price: 2950000,
        type: 'Passenger Vehicle',
        year: 2020,
        km: 65000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: 'Fleet Owner',
        location: 'Bangalore',
        sellerName: 'Capital Motors, Bangalore',
        dealerTrustStatus: 'Non-Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1623569567926-47b746654e5a?auto=format&fit=crop&q=80&w=400',
        description: 'Comfortable fleet passenger vehicle known for reliability.',
        variant: '2.4 G 7 STR',
        rto: 'KA-03',
        emi: '56,311',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Fleet Ready',
        specs: {
            engine: '2.4L Diesel',
            power: '148 bhp',
            torque: '343 Nm',
            mileage: '12 kmpl'
        }
    },
    {
        id: 'v4',
        name: 'Ashok Leyland Dost+',
        brand: 'Ashok Leyland',
        price: 750000,
        type: 'Commercial Vehicle',
        year: 2022,
        km: 15000,
        fuel: 'Diesel',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Delhi',
        sellerName: 'Northwest Commercials, Delhi',
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1609529669235-c07e4e1bd6e9?auto=format&fit=crop&q=80&w=400',
        description: 'Premium light commercial vehicle with advanced safety features.',
        variant: 'LS',
        rto: 'DL-01',
        emi: '13,861',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Low kms driven',
        specs: {
            engine: '1.5L Diesel',
            power: '80 bhp',
            torque: '190 Nm',
            payload: '1500 kg'
        },
        isAuction: true
    },
    {
        id: 'v5',
        name: 'Honda Activa 6G (Delivery Fleet)',
        brand: 'Honda',
        price: 65000,
        type: 'Two-Wheeler',
        year: 2022,
        km: 15000,
        fuel: 'Petrol',
        transmission: 'Automatic',
        owner: 'Fleet Owner',
        location: 'Pune',
        sellerName: 'Deshpande Commercials, Pune', // Same seller as v1
        dealerTrustStatus: 'Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1606161290610-c529a674d89a?auto=format&fit=crop&q=80&w=400',
        description: 'Ideal two-wheeler for delivery fleets. Batch purchasing available.',
        variant: 'Standard',
        rto: 'MH-14',
        emi: '1,542',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Bulk Available',
        specs: {
            engine: '109.51cc',
            power: '7.68 bhp',
            torque: '8.79 Nm',
            mileage: '50 kmpl'
        }
    },
    {
        id: 'v6',
        name: 'Bajaj RE Auto Rickshaw',
        brand: 'Bajaj',
        price: 250000,
        type: 'Commercial Vehicle',
        year: 2023,
        km: 2000,
        fuel: 'CNG',
        transmission: 'Manual',
        owner: '1st Owner',
        location: 'Pune',
        sellerName: 'AutoHub B2B Network Dealer',
        dealerTrustStatus: 'Non-Trusted Dealer',
        image: 'https://images.unsplash.com/photo-1594042878693-514add1d4411?auto=format&fit=crop&q=80&w=400',
        description: 'Economical three-wheeler for passenger transport.',
        variant: 'CNG 200cc',
        rto: 'MH-12',
        emi: '4,500',
        hubLocation: 'AutoHub B2B Network',
        conditionTag: 'Business Ready',
        specs: {
            engine: '236cc CNG',
            power: '9.5 hp',
            torque: '16.2 Nm',
            mileage: '40 km/kg'
        }
    }
];
